#include "Port.h"


#ifndef PORT_PBCFG_H_
#define PORT_PBCFG_H_

const Port_ConfigType Port_Configuration= {

	 PORT_A,PORT_PIN0,PORT_PIN_IN,PORT_A_PIN_0_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_A,PORT_PIN1,PORT_PIN_IN,PORT_A_PIN_1_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_A,PORT_PIN2,PORT_PIN_IN,PORT_A_PIN_2_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_A,PORT_PIN3,PORT_PIN_IN,PORT_A_PIN_3_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_A,PORT_PIN4,PORT_PIN_IN,PORT_A_PIN_4_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_A,PORT_PIN5,PORT_PIN_IN,PORT_A_PIN_5_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_A,PORT_PIN6,PORT_PIN_IN,PORT_A_PIN_6_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_A,PORT_PIN7,PORT_PIN_IN,PORT_A_PIN_7_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
       /*****************************PORT B**************************/ 
         PORT_B,PORT_PIN0,PORT_PIN_IN,PORT_B_PIN_0_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_B,PORT_PIN1,PORT_PIN_IN,PORT_B_PIN_1_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_B,PORT_PIN2,PORT_PIN_IN,PORT_B_PIN_2_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_B,PORT_PIN3,PORT_PIN_IN,PORT_B_PIN_3_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_B,PORT_PIN4,PORT_PIN_IN,PORT_B_PIN_4_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_B,PORT_PIN5,PORT_PIN_IN,PORT_B_PIN_5_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_B,PORT_PIN6,PORT_PIN_IN,PORT_B_PIN_6_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_B,PORT_PIN7,PORT_PIN_IN,PORT_B_PIN_7_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
        /**************************PORT C*************************/
	 PORT_C,PORT_PIN0,PORT_PIN_IN,PORT_C_PIN_0_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_C,PORT_PIN1,PORT_PIN_IN,PORT_C_PIN_1_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_C,PORT_PIN2,PORT_PIN_IN,PORT_C_PIN_2_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_C,PORT_PIN3,PORT_PIN_IN,PORT_C_PIN_3_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_C,PORT_PIN4,PORT_PIN_IN,PORT_C_PIN_4_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_C,PORT_PIN5,PORT_PIN_IN,PORT_C_PIN_5_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_C,PORT_PIN6,PORT_PIN_IN,PORT_C_PIN_6_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_C,PORT_PIN7,PORT_PIN_IN,PORT_C_PIN_7_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
          /*******************PORT D**********************/ 
         PORT_D,PORT_PIN0,PORT_PIN_IN,PORT_D_PIN_0_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_D,PORT_PIN1,PORT_PIN_IN,PORT_D_PIN_1_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_D,PORT_PIN2,PORT_PIN_IN,PORT_D_PIN_2_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_D,PORT_PIN3,PORT_PIN_IN,PORT_D_PIN_3_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_D,PORT_PIN4,PORT_PIN_IN,PORT_D_PIN_4_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_D,PORT_PIN5,PORT_PIN_IN,PORT_D_PIN_5_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_D,PORT_PIN6,PORT_PIN_IN,PORT_D_PIN_6_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_D,PORT_PIN7,PORT_PIN_IN,PORT_D_PIN_7_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         /*******************PORT E**********************/ 
         PORT_E,PORT_PIN0,PORT_PIN_IN,PORT_E_PIN_0_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_E,PORT_PIN1,PORT_PIN_IN,PORT_E_PIN_1_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_E,PORT_PIN2,PORT_PIN_IN,PORT_E_PIN_2_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_E,PORT_PIN3,PORT_PIN_IN,PORT_E_PIN_3_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_E,PORT_PIN4,PORT_PIN_IN,PORT_E_PIN_4_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_E,PORT_PIN5,PORT_PIN_IN,PORT_E_PIN_5_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         /*******************PORT F**********************/ 
         PORT_F,PORT_PIN0,PORT_PIN_IN,PORT_F_PIN_0_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_F,PORT_PIN1,PORT_PIN_OUT,PORT_F_PIN_1_DIR_CHANG,OFF,STD_LOW,PORT_PIN_MODE_DIO,             //Green LED
         PORT_F,PORT_PIN2,PORT_PIN_IN,PORT_F_PIN_2_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_F,PORT_PIN3,PORT_PIN_IN,PORT_F_PIN_3_DIR_CHANG,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,
         PORT_F,PORT_PIN4,PORT_PIN_IN,PORT_F_PIN_4_DIR_CHANG,PULL_UP,STD_LOW,PORT_PIN_MODE_DIO,        //BUTTON
        
};
#endif
        
      

	